<script type="ts">
    import { getTitle } from '$lib/global-functions';

    export let data;
    const { randomInt } = data;
</script>

<svelte:head>
    <title>{getTitle('Dynamic Server')}</title>
    <meta name="description" content="A dynamic page generated on the server" />
</svelte:head>

<div class="container">
    <h1>Dynamicly generated by the server</h1>
    <p style="max-width: 800px">
        This content is dynamicly generated by the server on build time. A client will always see the same number until
        a new build is triggered. The HTML sourcecode for this page also contains the same number shown below.
    </p>
    <p><b>{randomInt}</b></p>
</div>
