<script type="ts">
    import { getTitle } from '$lib/global-functions';

    export let data;
    const { hydratedContent } = data;
</script>

<svelte:head>
    <title>{getTitle('Dynamic Server-Client')}</title>
    <meta name="description" content="A dynamic page generated on the server and client" />
</svelte:head>

<div class="container">
    <h1>Dynamicly generated by the server and client</h1>
    <p style="max-width: 800px">
        This content is dynamicly generated by the server and the client. It will be generated by the server on build
        time and hydrated by the client with new information. The HTML sourcecode for this page contains the data
        generated by the server while the content shown to the client can vary (depending on what content is served). <br
        />
        <br />
        In this example the api will return a random programming joke. That means you will most likely see different content
        on this page as contained in the HTML sourcecode.
    </p>
    <p>
        {#if hydratedContent.error}
            AN ERROR OCCURED
        {:else}
            <pre><b>{hydratedContent.joke}</b></pre>
        {/if}
    </p>
</div>

<style>
    pre {
        font-family: sans-serif;
    }
</style>
