<script type="ts">
	export let randomInt: number;
	let url = 'https:google.com';
</script>

<div class="container">
	<h1>Dynamicly generated by the server</h1>
	<p style="max-width: 800px">
		This content is dynamicly generated by the server on build time. A client will always see the
		same number until a new build is triggered. The HTML sourcecode for this page also contains the
		same number shown below.
	</p>
	<p><b>{randomInt}</b></p>
</div>
