<script type="ts">
	const ip = fetch('https://api.my-ip.io/ip').then((resp) => resp.text());
</script>

<div class="container">
	<h1>Dynamicly generated on the client</h1>
	<p style="max-width: 800px">
		This content is dynamicly generated on the client. The HTML sourcecode for this page just
		contains a loading string while the content is generated by the client. After hydration the
		loading string will be replaced with the actual content by the client. <br />
		<br />
		In this example the api will return the requests origin IP.
	</p>
	{#await ip}
		Waiting for data from api server
	{:then ip}
		Data from api server: {ip}
	{:catch}
		Something went wrong.
	{/await}
</div>
